# Simplified Docker Compose for initial testing
# This is a minimal configuration to test basic functionality

services:
  torch-inference:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: torch-inference-server
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
      - ENVIRONMENT=development
      - LOG_LEVEL=INFO
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

# Simple volume for logs
volumes:
  logs:
    driver: local