# Development Docker Compose
version: '3.8'

services:
  torch-inference:
    build:
      context: ..
      dockerfile: docker/Dockerfile.dev
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=development
      - LOG_LEVEL=DEBUG
    volumes:
      - ../src:/app/src
      - ../framework:/app/framework
      - ../logs:/app/logs
      - ../models:/app/models
      - ../cache:/app/cache
    restart: "no"
    stdin_open: true
    tty: true

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
