# Production Configuration

# Override default settings for production
debug: false
environment: "production"

server:
  reload: false
  log_level: "INFO"
  workers: 4

security:
  enable_rate_limiting: true
  max_requests_per_minute: 1000
  enable_cors: true
  allowed_origins:
    - "https://yourdomain.com"
    - "https://app.yourdomain.com"
    # Note: Configure these URLs for your specific production domains

logging:
  level: "INFO"
  file_logging: true
  
# Production-specific features
features:
  enable_debug_endpoints: false
  detailed_error_responses: false
  enable_metrics: true
  enable_monitoring: true
